repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-added-large-files

  # Rust tooling via local hooks to use your system's Cargo
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt (check)
        entry: cargo fmt --all --
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy (deny warnings)
        entry: cargo clippy --all-targets --all-features --fix --allow-dirty -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false

      # Run tests on push to keep commits snappy
      - id: cargo-test
        name: cargo test (quick)
        entry: cargo test -q
        language: system
        pass_filenames: false
        stages: [pre-push]
