[package]
name = "browser-demux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
freedesktop-desktop-entry = "0.5.0"
clap = { version = "4.1", features = ["derive"] }
anyhow = "1.0"
wildflower = "0.1.1"
