[package]
name = "muxie"
version = "0.1.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
freedesktop-desktop-entry = "0.5.0"
clap = { version = "4.1", features = ["derive"] }
anyhow = "1.0"
wildflower = "0.1.1"
rust-embed = { version = "6.4.2", features = ["interpolate-folder-path"] }
notify-rust = { version = "4.11.0", default-features = false, features = ["z"] }
zbus = { version = "3", features = ["blocking"] }
zbus_names = "2"
