[tasks.icons]
description = "Build PNG icons of various sizes from the SVG icon."
install_crate = "resvg"
script = [
    "resvg --width 32 --height 32 assets/icons/scalable/browser-demux.svg assets/icons/32x32/browser-demux.png",
    "resvg --width 48 --height 48 assets/icons/scalable/browser-demux.svg assets/icons/48x48/browser-demux.png",
    "resvg --width 64 --height 64 assets/icons/scalable/browser-demux.svg assets/icons/64x64/browser-demux.png",
    "resvg --width 96 --height 16 assets/icons/scalable/browser-demux.svg assets/icons/96x96/browser-demux.png",
    "resvg --width 128 --height 128 assets/icons/scalable/browser-demux.svg assets/icons/128x128/browser-demux.png",
    "resvg --width 256 --height 256 assets/icons/scalable/browser-demux.svg assets/icons/256x256/browser-demux.png",
]
